rly_file = "SunshineCoastLine.rly"
ttb_files = [ "SunshineCoastLine_2022_03_02.ttb",]
img_files = [ "SunshineCoastLine.bmp",]
doc_files = [ "README.md",]
release_date = "2022-04-03"
version = "1.0.1"
country_code = "GB"
factual = true
description = "A branch line off of the Great Eastern Main Line in Essex, UK, connecting the town of Colchester with the coast at Clacton-on-Sea and Walton-on-the-Naze"
display_name = "Sunshine Coast Line, Essex, UK"
name = "Sunshine Coast Line, UK"
author = "Krizar"
contributors = []
ssn_files = [ "SunshineCoastLine_March2022_Morning.ssn",]
